### ISSUE TITLE
Überschriften im fertigen Alias.txt

### ISSUE THREAD

**Issue by jannikvogel** [VATGER-Nav/aliases#24]
Können die Überschriften im generierten Alias File bitte entfernen? Sonst müssen diese händisch entfernt werden, so dass sie korrekt in GNG verarbeitet werden können.

**Comment by LeoKle** [comment]
Magst du einmal spezifizieren, inwiefern die Datei nicht richtig verarbeitet wird?

**Comment by jannikvogel** [comment]
> Magst du einmal spezifizieren, inwiefern die Datei nicht richtig verarbeitet wird?

Copy-Paste der hier generierten Datei spuckt bei mir folgenden Fehler in GNG aus...komisch, dass das sonst niemand hat/hatte

https://i.imgur.com/T7RcOQG.png

**Comment by jannikvogel** [comment]
Sobald mal die Zeilen mit Überschriften manuell entfernt, wird die Datei verarbeitet.

**Comment by LeoKle** [comment]
Ein Semikolon davor verhindert das Problem. Würde entsprechend ein Semikolon hinzufügen, damit wir die Lesbarkeit / Abgrenzung beibehalten.

**Comment by jannikvogel** [comment]
Fein für mich. Eine Lösung für den Syntaxfehler wäre schön, wie die aussieht ist mir persönlich recht egal
