### ISSUE TITLE
Use euroscope built in functions

### ISSUE THREAD

**Issue by jannikvogel** [VATGER-Nav/aliases#4]
Im Moment nutzen wir nicht die built in functions von Euroscope, durch die man sich sehr viel getippe sparen kann. Z. Bsp. bei Level Instructions. Hier könnte man $temp verwenden, um das CFL aus dem System automatisch ins Alias zu bringen.

Details siehe hier: https://www.euroscope.hu/wp/built-in-functions/

**Comment by fpletz** [comment]
Fixed by #2.
