### ISSUE TITLE
Phraseology issues

### ISSUE THREAD

**Issue by gShooh** [VATGER-Nav/aliases#7]
Hello!
Here are some points I wanted to discuss. 

1. In line 154 as well as in line 184 it says "active runway"/"aktive Piste".
According to the current AIP, GEN 3.4 - 1.1.11, it is not "active runway"/"aktive Piste", it is only: "runway"/"Piste".

2. The second point is that there should be an alias in the delivery part that makes it possible to release a IFR clearens with the startup, because it avoids nessecery time as well as trouble during normal operation. 

An example or possibility would be: 
.cls Startup approved, cleared to $arr, $sid departure, flight planned route, climb to $temp, squawk $squawk.
.clrvs Startup approved, cleared to $arr, $sid departure, flight planned route, climb via SID to $temp, squawk $squawk.

3. Line 217: "Sofort anhalten. Halten Sie Position, Startfreigabe aufgehoben."  <- According to AIP GEN 3.4 - 1.4.11, it should be either "Halten Sie Position, Startfreigabe aufgehoben, ich wiederhole, Startfreigabe aufgehoben." or "Sofort anhalten, RUFZEICHEN, sofort anhalten.". I don't know which of the two is mean by this one, however, you should choose between one of the two, and then word it according to AIP. 

5. Line 231: .dcol Verlassen der Frequenz genehmigt. <- Squawk VFR should also be included, or a further alias. (Same in line 181)

6. General point, why are there less english VFR aliases than in german? If you already offer DE and EN, all aliases which are available in german should also be in english to avoid misunderstandings at the controller. 

7. ".downex Extend downwind, standby for base." <- There should also also be an alias with a right downwind and a right base.

I know that there are much more mistakes inside, but I will not explain them all. I hope that you rework these aliases again with the AIP.

**Comment by capzDE** [comment]
> In line 154 as well as in line 184 it says "active runway"/"aktive Piste".
According to the current AIP, GEN 3.4 - 1.1.11, it is not "active runway"/"aktive Piste", it is only: "runway"/"Piste".

Definitely something we should update at some point.

> The second point is that there should be an alias in the delivery part that makes it possible to release a IFR clearens with the startup, because it avoids nessecery time as well as trouble during normal operation.

I'm personally not a big fan of giving startup together with the enroute clearance. If anything, I'd rather add a combined startup/pushback alias.

> Line 217: "Sofort anhalten. Halten Sie Position, Startfreigabe aufgehoben." <- According to AIP GEN 3.4 - 1.4.11, it should be either "Halten Sie Position, Startfreigabe aufgehoben, ich wiederhole, Startfreigabe aufgehoben." or "Sofort anhalten, RUFZEICHEN, sofort anhalten.". I don't know which of the two is mean by this one, however, you should choose between one of the two, and then word it according to AIP.

The idea here was to combine these two to have one alias that fits any cancellation of the takeoff clearance, regardless of whether traffic is already rolling or not (the "Halten Sie Position" one is for when the takeoff roll hasn't begun yet, whereas "Sofort anhalten" is for when the aircraft is already on the roll). As for the repetitions, I don't really see the point in adding them considering it is meant to avoid confusion/pilots overhearing the instruction/etc. which isn't an issue with text.

> Line 231: .dcol Verlassen der Frequenz genehmigt. <- Squawk VFR should also be included, or a further alias. (Same in line 181)

Adding "Squawk VFR" here, however, would mean that the alias doesn't cover situations in which traffic hasn't gotten a separate squawk anymore. If they did, adding a quick .sqv afterwards shouldn't be too big of an issue in my opinion.

> General point, why are there less english VFR aliases than in german? If you already offer DE and EN, all aliases which are available in german should also be in english to avoid misunderstandings at the controller.

The simple answer is that the German VFR aliases also include some whose English variants are already covered elsewhere (e.g. taxi instructions in English are already covered under the Ground category).

> ".downex Extend downwind, standby for base." <- There should also also be an alias with a right downwind and a right base.

Good point!

**Comment by gShooh** [comment]
Thank you very much first of all for the answer. 

> I'm personally not a big fan of giving startup together with the enroute clearance. If anything, I'd rather add a combined startup/pushback alias.

Ok, but I don't care what you personally like ;) . It is applied in reality every day and it is not possible at airports like Munich or Dresden to give pushback and startup at the same time. 
It saves an abnormal amount of time and effort. Up to you, but it makes no sence. 


> The idea here was to combine these two to have one alias that fits any cancellation of the takeoff clearance, regardless of whether traffic is already rolling or not (the "Halten Sie Position" one is for when the takeoff roll hasn't begun yet, whereas "Sofort anhalten" is for when the aircraft is already on the roll). As for the repetitions, I don't really see the point in adding them considering it is meant to avoid confusion/pilots overhearing the instruction/etc. which isn't an issue with text.

The problem we see is that we teach our trainees correct phraseolgy. If there are phrseological errors in the aliases given from above, we don't need to teach it to the trainees. Think about it.

**Comment by capzDE** [comment]
> Ok, but I don't care what you personally like ;) . It is applied in reality every day and it is not possible at airports like Munich or Dresden to give pushback and startup at the same time.
It saves an abnormal amount of time and effort. Up to you, but it makes no sence.

Sure, and after all, it's just my opinion which isn't the deciding factor in the end, but opinions are important to find a decision that works for everyone, especially in a communal project like this alias file.
However, while certainly possible, giving startup together with the enroute clearance is a very unusual occurence (as confirmed by multiple real world pilots and ATCOs). I can see the use case for topdown, but whether you give the startup clearance together with the pushback or with the enroute clearance doesn't really make a difference, you still have to use two aliases overall. In conjunction with the second part of your message, it might actually teach things incorrectly to your trainees (especially at ACDM airports like DM where you virtually never have both in the same message unless it's an instruction like "startup approved according TSAT" maybe, which, while I would very much like that, doesn't work very well with VATSIM pilots).
What prevents you from using a combined startup and pushback instruction at DM and DC?

> The problem we see is that we teach our trainees correct phraseolgy. If there are phrseological errors in the aliases given from above, we don't need to teach it to the trainees. Think about it.

I can understand that, but do you point your trainees to the alias file to learn the phraseology? In my opinion and experience, the alias file is not a good tool to learn the proper phraseology and never was, either.
How would you go about getting this alias more in line with the AIP, though? Would you want to split it into two separate aliases? Put in one instruction but completely leave out the other? I personally feel like the combined one is a good compromise for an alias that will only be used very rarely anyways: the instruction will reasonably fit the situation regardless of whether traffic is moving or not and as one singular alias, it's easier to remember. But maybe there are options/arguments I missed?

In that regard, though:
> I know that there are much more mistakes inside, but I will not explain them all. I hope that you rework these aliases again with the AIP.

Please feel free to point these out when you notice them. I don't know about the other people who did some work on this alias file, but I only crosschecked the ones that I wasn't 100% sure about, so there definitely was some room for human error.

**Comment by capzDE** [comment]
Oh, and if you don't mind, I'll reopen this issue so that it stays in the list and we don't forget about it :D

**Comment by gShooh** [comment]
> Sure, and after all, it's just my opinion which isn't the deciding factor in the end, but opinions are important to find a decision that works for everyone, especially in a communal project like this alias file.
However, while certainly possible, giving startup together with the enroute clearance is a very unusual occurence (as confirmed by multiple real world pilots and ATCOs). I can see the use case for topdown, but whether you give the startup clearance together with the pushback or with the enroute clearance doesn't really make a difference, you still have to use two aliases overall. In conjunction with the second part of your message, it might actually teach things incorrectly to your trainees (especially at ACDM airports like DM where you virtually never have both in the same message unless it's an instruction like "startup approved according TSAT" maybe, which, while I would very much like that, doesn't work very well with VATSIM pilots).
What prevents you from using a combined startup and pushback instruction at DM and DC?

Correct, however the problem with airports like this that they only have an apron controller, they are not allowed to give startup as an apron. So, for logical reasons, we will not give a startup with the pushback. It is a standard procedure in Munich to distribute startup with clearens (on VATSIM), they don´t use ACDM as standard, only at events. I know if you do topdown you can argue about it, still it's just a .clrs/.clrvs . Where is the big problem ;) . It's just 3 words more. 


> I can understand that, but do you point your trainees to the alias file to learn the phraseology? In my opinion and experience, the alias file is not a good tool to learn the proper phraseology and never was, either.

I have now been asked by 2 trainees what is correct because it is written different in the aliases. It is not a learning tool, but everything should still be correct, as it is simply a "role model". I have myself as a trainee partly the radio messages (especially VFR) first prescribed and then looked at how I speak it. Of course, you should not do that, but it is done that way by some trainees. 

-- 

Anyway, I'm not going to extend this longer. You can think about it or add it, or not. The additional points mentioned below are small things, which I do not want to list all, because it is not the responsibility of me, and I see no benefit in it. They are mainly filling words or even half correct application of the AIP, but nothing big. 

Thank you for the extensive discussion and the time. 
Kind regards!

**Comment by capzDE** [comment]
> Correct, however the problem with airports like this that they only have an apron controller, they are not allowed to give startup as an apron. So, for logical reasons, we will not give a startup with the pushback.

Interesting, this sounds like a different approach then. In Frankfurt, if Apron covers Delivery topdown, we don't care whether they do this combined since - technically - they are also Delivery and thus may give the startup. IRL, it's also not uncommon for Apron and Delivery to simply coordinate if pilots switch prematurely, have missed their TSAT, etc. and with appropriate approval from Delivery, they can also communicate that startup clearance to the pilot - not sure if it's the same at DM/DC, of course. (Did we discuss that on Thursday before last week during the sim? Did I miss/already forget that? 😅)

> Where is the big problem ;) . It's just 3 words more.

Sure, but since other places rather give startup with the pushback in situations as the one you described above, my thought was that adding a combined push and start alias would be more efficient overall. However, I can definitely understand why it would make sense for you guys to have a combined clearance and startup alias then.
The problem of people just randomly giving startup without pilots actually requesting it is ultimately also more an ATC training issue than a topdown/alias one.
